### ISSUE TITLE
CLI options

### ISSUE THREAD

**Issue by Robotato** [CovertLab/vEcoli#29]
This list represents options that are intended to be added to the command line interface for vivarium-ecoli.

**Options taken from wcEcoli:**

- [x] random seed (-seed SEED)
- [x] number of generations (-g GENERATIONS)
- [x] length of simulation in seconds (--length-sec LENGTH_SEC)
- [ ] variant (-?)
- [ ] whether to enable growth rate noise (--growth-rate-noise)
- [ ] environmental perturbation timeline (-t TIMELINE)
- [x] path to sim_data ([SIM_DIR])

**New in vivarium-ecoli:**

- [x] database emitter (-?)
- [x] modifying parameter values (possibly -<process_name> PARAMETER_PATH PARAMETER_VALUE ?)
- [x] model customization and swapping (details subject to change)
  - inclusion/removal: (-models MODEL_NAMES) (-exclude MODEL_NAMES)
  - swapping (-<model_name> VARIANT_NAME)

**Comment by thalassemia** [comment]
De-prioritized CLI in favor of unified JSON configuration interface.
